version: "3"
services:
  mongodb:
     image: mongo
     ports:
      - "27017:27017"
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app-restful
    ports:
      - "5000:5000"